### ISSUE TITLE
issue about cnn-a_solver.prototxt

### ISSUE THREAD

**Issue by zhanglichao** [scott89/STCT#1]
Hi Lijun,

Thank u very much for your code and paper. I've read your 2 tracking papers(ICCV2015 & CVPR2016), which are very admirable!

While I meet a problem about the STCT: when it runs the caffe_.mexa64 (which is well compiled by caffe installation) through cnn-a_solver.prototxt, it reports error, which is *\* MATLAB has encountered an internal problem and needs to close**.
I tried two well compiled machines, but it comes the same problems.

Appreciate it a lot for your valuable and kind favor.

All the best,
Lichao

**Comment by scott89** [comment]
Hi Lichao,

I have read your e-mail. Could you please provide more details on the error. In particular, please provide the error message returned by Caffe to the Terminal. 

Best regards,

Lijun

**Comment by zhanglichao** [comment]
Hi Lijun,

Thank you very much for your reply.
The error message from the Terminal is as below: 
......
solver_mode: GPU
device_id: 0
random_seed: 701
net: "model/cnn-a.prototxt"
I0505 11:49:01.069391  2490 solver.cpp:91] Creating training net from net file: model/cnn-a.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 44:9: Message type "caffe.ConvolutionParameter" has no field named "mask".
F0505 11:49:01.069466  2490 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: model/cnn-a.prototxt
**\* Check failure stack trace: ***
Killed
.......

Thanks again for your kind help!

All the best,
Lichao

**Comment by scott89** [comment]
Hi Lichao,

The error is caused by the "mask" parameter of convolution layer, which is not defined in the official version of Caffe.  To solve this issue, you have to adopt my modified version of [Caffe](https://github.com/scott89/caffe/tree/181a655dc9a0b573abf06fc005b3c62ea3f9fd33).

**Comment by zhanglichao** [comment]
Hi Lijun,

Thank u so much.
OKay, I have a try..

best,
Lichao

**Comment by zhanglichao** [comment]
Hi Lijun,

Finally, it works. So excited!!!!!!!!!!!!!!!
So many thanks to u!!!

best,

Lichao

**Comment by mashreve** [comment]
Hi, I am getting this exact error. I compiled the modified caffe version you linked to: https://github.com/scott89/caffe/tree/181a655dc9a0b573abf06fc005b3c62ea3f9fd33. 

I0919 11:07:48.610445 18529 solver.cpp:70] Creating training net from net file: model/cnn-a.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 44:9: Message type "caffe.ConvolutionParameter" has no field named "mask".
F0919 11:07:48.610527 18529 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: model/cnn-a.prototxt
**\* Check failure stack trace: ***
^C
[2]+  Killed                  matlab  (wd: ~)
(wd now: ~/STCT/model)

Any suggestions?

Thank you,
Matthew

**Comment by mashreve** [comment]
Hello again, just solved my previous issue:

If you use " >git clone https://github.com/scott89/caffe.git " to acquire caffe, it does not work. I downloaded the zip file and it did work.

Thanks for the great tracker!

**Comment by scott89** [comment]
Hi Matthew,
Please make sure that both caffe and matcaffe have been well compiled. It seems that you are not using my modified caffe version, since the mask field has already been added to ConvolutionParameter in my version. Also make sure that your are using the latest network definition format (Not that "layers" are old V0 versions. The latest net definition in prototxt files use "layer" ).

**Comment by scott89** [comment]
Use "git clone --recursive" to clone STCT will simultaneously clone caffe submodule.
