### ISSUE TITLE
caffe install errors

### ISSUE THREAD

**Issue by ghost** [scott89/STCT#3]
Hi, thank you for your sharing,It is a great job~
  And when i try to follow the instruction to install the caffe  in the STCT dir,i encountered many problem(so do the FCNT).perhaps the caffe you recommended is too old?I use the latest version of cudnn & cuda,(ps:the latest version of caffe i have installed),and i just want to know:must i use the caffe you recommend?Can i use the latest version of caffe?(and FCNT too?) .Thx again~

**Comment by scott89** [comment]
Hi! Both STCT and FCNT are developed based on modified versions of the Caffe framework. Therefore, in order to run these trackers, you have to first install the modified Caffe included in the repos. The STCT has been tested and runs well with  Cuda 7.5.

**Comment by ghost** [comment]
Oh,i see,maybe i should solve these problems one by one~ and thank you for
your great sharing again~

2016-12-08 10:02 GMT-05:00 scott89 <notifications@github.com>:

**Comment by scott89** [comment]
You are welcome. If you have any further problem in installing the code, feel free to post them here.
