### ISSUE TITLE
caffe install

### ISSUE THREAD

**Issue by hanyamin** [scott89/STCT#5]
Hi Lijun,
When I install caffe you provided, I got some troubles.  when I executed the order "make runtest" . I got some errors as follows
[ RUN      ] CuDNNConvolutionLayerTest/1.TestSimpleConvolutionCuDNN
F0329 08:59:17.664275 41802 cudnn.hpp:92] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM

The environments is as follows:
OS: Centos 7.0 64bit
cuda 7.5
cudnn4.0

Thanks

**Comment by scott89** [comment]
Dear Hanyamin,

The error encountered in "make runtest" maybe caused by the conflict of CuDNN versions. Since our released source code uses a modified version of Conv and cannot use CuDNN engine, you can set the macro USE_CUDNN in Makefile.config to 0.

**Comment by hanyamin** [comment]
Thanks
