### ISSUE TITLE
Message type "caffe.ConvolutionParameter" has no field named "mask"

### ISSUE THREAD

**Issue by xiaoqiao728295** [scott89/STCT#6]
Dear author,

I have complied Caffe successfully, but when i run demo_STCT, i got the problem:Error parsing text-format caffe.NetParameter: 44:9: Message type "caffe.ConvolutionParameter" has no field named "mask". 
Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: model/cnn-a.prototxt

What's the matter about that? Could you give some advice?

**Comment by scott89** [comment]
Hi! I think you might adopt Caffe of a wrong version. I suggest you clone the STCT repository using:
```
git clone --recursive https://github.com/scott89/STCT.git
```
Then compile Caffe contained in the repository.

Thanks
